### ISSUE TITLE
Error in overlays.xml

### ISSUE THREAD

**Issue by yamboo-efi** [dsiggi/RocketRAID#1]
Hi,

The file overlays.xml has an error. In order to work you need to remove the first part because with it layman do a parsing error. A right content would be:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repositories SYSTEM "/dtd/repositories.dtd">
<repositories xmlns="" version="1.0">
  <repo quality="experimental" status="unofficial">
    <name>RocketRAID</name>
    <description lang="en">Kernel mdules for many RocketRaid cards and the client and server software.</description>
    <owner type="person">
      <email></email>
      <name>dsiggi</name>
    </owner>
    <source
    type="git">git://github.com/dsiggi/RocketRAID</source>
   </repo>
</repositories>
```
I downloaded the file, edited it, and change the layman.conf to load the overlay from the downloaded file. Additionaly to add the overlay, the correct name would be "RocketRAID". In other way, the overlay work like a charm, I'm tested it in kernel 4.0.5 and with a rocket raid 2340. 

Good work!!

**Comment by dsiggi** [comment]
I've editet the overlys.xml. Thank's for your message.

**Comment by yamboo-efi** [comment]
I've edited the Wiki to correct the overlay name. Thanks for your quick correction. 


     El Domingo 9 de agosto de 2015 21:05, dsiggi <notifications@github.com> escribió:
   

 I've editet the overlys.xml. Thank's for your message.—
