### ISSUE TITLE
Missing device ID for rr62x

### ISSUE THREAD

**Issue by rkjnsn** [dsiggi/RocketRAID#3]
(This is clearly an upstream omission, but since the driver seems abandoned, I figured I'd see if it could be addressed here.)

The rr62x driver has two PCI ids: `1103:0620` and `1103:0622`. However, by RocketRAID 622 has a different vendor ID: `1b4b:0622`. While the module still works if I load it manually, it won't automatically get picked up at boot. The following patch fixes it for me. Any chance it could be included in the repo?

```diff
--- product/rr62x/linux/config.c	2012-05-31 22:55:35.000000000 -0700
+++ product/rr62x/linux/config.c	2018-01-28 15:07:37.120419777 -0800
@@ -32,6 +32,7 @@
 static const struct pci_device_id hpt_pci_tbl[] = {
 	{PCI_DEVICE(0x1103, 0x0620), 0, 0, 0},
 	{PCI_DEVICE(0x1103, 0x0622), 0, 0, 0},
+	{PCI_DEVICE(0x1b4b, 0x0622), 0, 0, 0},
 	{}
 };
 MODULE_DEVICE_TABLE(pci, hpt_pci_tbl);
```

**Comment by dsiggi** [comment]
Thanks for your message. I've added your patch to the source.
