### ISSUE TITLE
Make error on kernel 4.15

### ISSUE THREAD

**Issue by eriksson25** [dsiggi/RocketRAID#6]
Tried to compile rr2340 drivers for ubuntu 18.04.02, with kernel 4.15.0-46

It patches fine, but wount compile. Following error

`eriksson25@eriksson25:~/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux$ sudo make
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-46-generic'
  CC [M]  /home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o
/home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.c:1:0: error: code model kernel does not support PIC mode
 /* $Id: os_linux.c,v 1.33 2009/02/18 01:26:29 zsf Exp $
 ^
scripts/Makefile.build:332: recipe for target '/home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o' failed
make[2]: *** [/home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o] Error 1
Makefile:1551: recipe for target '_module_/home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build' failed
make[1]: *** [_module_/home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-46-generic'
../../../inc/linux/Makefile.def:102: recipe for target 'rr2340.ko' failed
make: *** [rr2340.ko] Error 2
`

**Comment by dsiggi** [comment]
Hi,
did you build this kernel by your self or is this the default kernel of ubuntu?
Which gcc version did you use?

Daniel

**Comment by eriksson25** [comment]
> Hi,
> did you build this kernel by your self or is this the default kernel of ubuntu?
> Which gcc version did you use?
> 
> Daniel

Its a fresh 18.04.02 install with default kernel.

I have following gcc installed.

`dpkg --get-selections | grep gcc
gcc                                             install
gcc-7                                           install
gcc-7-base:amd64                                install
gcc-8                                           install
gcc-8-base:amd64                                install
gcc-8-doc                                       install
gcc-8-multilib                                  install
lib32gcc-8-dev                                  install
lib32gcc1                                       install
libgcc-7-dev:amd64                              install
libgcc-8-dev:amd64                              install
libgcc1:amd64                                   install
libx32gcc-8-dev                                 install
libx32gcc1                                      install
`
Dont  know which one is used.

**Comment by dsiggi** [comment]
It seems that gcc6+ has PIE enabled by default and this is the problem.

See here:
https://askubuntu.com/questions/851433/kernel-doesnt-support-pic-mode-for-compiling

You can test this:
Run the make command for the module like this:
$ make CFLAGS='-fno-pie'

Daniel

**Comment by eriksson25** [comment]
> It seems that gcc6+ has PIE enabled by default and this is the problem.
> 
> See here:
> https://askubuntu.com/questions/851433/kernel-doesnt-support-pic-mode-for-compiling
> 
> You can test this:
> Run the make command for the module like this:
> $ make CFLAGS='-fno-pie'
> 
> Daniel

Yes, have read about it and tried to add it to the make file with no result. Have removed again. Also tried as you wrote it with no diffrence...

**Comment by eriksson25** [comment]
> It seems that gcc6+ has PIE enabled by default and this is the problem.
> 
> See here:
> https://askubuntu.com/questions/851433/kernel-doesnt-support-pic-mode-for-compiling
> 
> You can test this:
> Run the make command for the module like this:
> $ make CFLAGS='-fno-pie'
> 
> Daniel

Just found this https://askubuntu.com/questions/911538/disable-pie-and-pic-defaults-in-gcc-on-ubuntu-17-04 
and tried sudo make -no-pie

And i think it compiled. No errors anyway. So will try to add the driver now and report back.

**Comment by eriksson25** [comment]
> It seems that gcc6+ has PIE enabled by default and this is the problem.
> 
> See here:
> https://askubuntu.com/questions/851433/kernel-doesnt-support-pic-mode-for-compiling
> 
> You can test this:
> Run the make command for the module like this:
> $ make CFLAGS='-fno-pie'
> 
> Daniel

Hmm, still something is wierd...

The make ends with `
cp -f /home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/.build/rr2340.ko /home/eriksson25/rr2340-linux-src-v1.7-090925-0900/rr2340-linux-src-v1.7/product/rr2340/linux/
`

So it looks good, but then there is no rr2340.ko file in the folder. Dont understand...

**Comment by eriksson25** [comment]
Okey, some developments.

Decided to try and redo everything... So fresh drivers, patch with your lates and then sudo make -no-pie

Gives me error .build does not exist.

If I do just sudo make, then .build is created but gives me now following error

`eriksson25@eriksson25:~/rr2340-linux-src-v1.7/product/rr2340/linux$ sudo make
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-46-generic'
  CC [M]  /home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o
/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.c: In function ‘os_request_timer’:
/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.c:574:27: error: assignment to ‘void (*)(struct timer_list *)’ from incompatible pointer type ‘void (*)(long unsigned int)’ [-Werror=incompatible-pointer-types]
  vbus_ext->timer.function = os_timer_for_ldm;
                           ^
/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.c:575:17: error: ‘struct timer_list’ has no member named ‘data’
  vbus_ext->timer.data = (unsigned long)vbus_ext;
                 ^
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o' failed
make[2]: *** [/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o] Error 1
Makefile:1551: recipe for target '_module_/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build' failed
make[1]: *** [_module_/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-46-generic'
../../../inc/linux/Makefile.def:102: recipe for target 'rr2340.ko' failed
make: *** [rr2340.ko] Error 2
`

**Comment by dsiggi** [comment]
At first, you can normaly do the make command without sudo.

It seems that you forgot the patch from ubuntuforums (This one for the timer, #5 )
At the moment you find this patch in this repo only for rr232x and rr64x. For your card (rr2340) you have to patch it by your self.

Daniel

**Comment by eriksson25** [comment]
> At first, you can normaly do the make command without sudo.
> 
> It seems that you forgot the patch from ubuntuforums (This one for the timer, #5 )
> At the moment you find this patch in this repo only for rr232x and rr64x. For your card (rr2340) you have to patch it by your self.
> 
> Daniel

ahh... I have read your wiki wrong... Thought you had fixed all modules since all of them got updated at the same time... Now that makes more sense when reading the wiki.

Would you take donation to fix 2340? Dont know enugh to figure out the timings (have compared the rr232x and rr64x timing patch).

**Comment by dsiggi** [comment]
I take no donation for this.
I will have a look on it tomorrow.

**Comment by eriksson25** [comment]
> I take no donation for this.
> I will have a look on it tomorrow.

Then you are a hero, and if you like i could donate to a "charity" instead. Your help is highly appreciated.

**Comment by dsiggi** [comment]
Hi,
download this patch: https://raw.githubusercontent.com/dsiggi/RocketRAID/master/sys-block/rr2340/files/rr2340-timer.patch

First patch the "old" patch named rr2340-kernel-4-x.patch and then the "new" patch.
Then run the make command without sudo.

I hope this will solve your problem.

Daniel

**Comment by eriksson25** [comment]
> Hi,
> download this patch: https://raw.githubusercontent.com/dsiggi/RocketRAID/master/sys-block/rr2340/files/rr2340-timer.patch
> 
> First patch the "old" patch named rr2340-kernel-4-x.patch and then the "new" patch.
> Then run the make command without sudo.
> 
> I hope this will solve your problem.
> 
> Daniel
Thank you, I think its almost there....

I got the following error

`eriksson25@eriksson25:~/rr2340-linux-src-v1.7/product/rr2340/linux$ make
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-46-generic'
  CC [M]  /home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/os_linux.o
  CC [M]  /home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/osm_linux.o
/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/osm_linux.c: In function ‘hpt_detect’:
/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/osm_linux.c:328:1: error: invalid use of void expression
 +  timer_setup(&vbus_ext->timer, 0 ,0);
 ^
scripts/Makefile.build:332: recipe for target '/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/osm_linux.o' failed
make[2]: *** [/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build/osm_linux.o] Error 1
Makefile:1551: recipe for target '_module_/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build' failed
make[1]: *** [_module_/home/eriksson25/rr2340-linux-src-v1.7/product/rr2340/linux/.build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-46-generic'
../../../inc/linux/Makefile.def:102: recipe for target 'rr2340.ko' failed
make: *** [rr2340.ko] Error 2
`

**Comment by dsiggi** [comment]
Aahh, it's my fault.
There's a "+" to much in line 54 of the rr2340-timer.patch. Download this patch again, please.
Then unpack the module source again und patch the two patches.

Daniel

**Comment by eriksson25** [comment]
> Aahh, it's my fault.
> There's a "+" to much in line 54 of the rr2340-timer.patch. Download this patch again, please.
> Then unpack the module source again und patch the two patches.
> 
> Daniel

It works! Thank you sooooo mutch!

**Comment by dsiggi** [comment]
Great, nice that it works. Have fun with your rocketraid-card.

**Comment by eriksson25** [comment]
> Hi,
> download this patch: https://raw.githubusercontent.com/dsiggi/RocketRAID/master/sys-block/rr2340/files/rr2340-timer.patch
> 
> First patch the "old" patch named rr2340-kernel-4-x.patch and then the "new" patch.
> Then run the make command without sudo.
> 
> I hope this will solve your problem.
> 
> Daniel
It was almost perfect...
Just to others geting same problem
Loading the module gave me following error.

`modprobe: ERROR: could not insert 'rr2340': Unknown symbol in module, or unknown parameter (see dmesg)`

When I check dmesg it says
`rr2340: Unknown symbol sev_enable_key (err 0)`

Found the following, https://ubuntuforums.org/archive/index.php/t-2404643.html
And using the tip in last post it is now working.
