### ISSUE TITLE
See Fedora thread for Linux 5 support

### ISSUE THREAD

**Issue by fire** [dsiggi/RocketRAID#7]
https://askubuntu.com/questions/1001963/rocketraid-640-ubuntu-16-04-kernel-4-13-support

**Comment by fire** [comment]
Oops wrong link. https://forums.fedoraforum.org/showthread.php?321570-Fedora-30-Server-Installer-Doesn-t-See-RocketRaid-620/page2

**Comment by fire** [comment]
[rr64x-5.0.patch.txt](https://github.com/dsiggi/RocketRAID/files/4029285/rr64x-5.0.patch.txt)

http://highpoint-tech.com/BIOS_Driver/RR64xL/Linux/RR64xl_Linux_Src_v1.4.0_16_09_20.tar.gz

**Comment by dsiggi** [comment]
Thank you for your submission
