### ISSUE TITLE
r750

### ISSUE THREAD

**Issue by dafrenchyman** [dsiggi/RocketRAID#8]
If you could pull off a patch for Rocketraid 750 that would be awesome. I've been messing around trying to make one for the past few days with no luck (how I found you). I'll help anyway I can.

**Comment by dsiggi** [comment]
Hi,
I have to look if I can use the patchset from here as base.

**Comment by dsiggi** [comment]
Hi,
I get the module build up to kernel 4.19.

For kernel <4.15 the module build out of the box.

For kernel >4.15 and <4.17 patch the file "kernel-4.15.patch"

For kernel >4.17 patch files "kernel-4.15.patch", "pci_get_domain_bus_and_slot.patch" and "kernel-4.17.patch"

I uploaded the patches for testing: [r750_patches.zip](https://github.com/dsiggi/RocketRAID/files/4147756/r750_patches.zip)

Please feel free to test and write here if it work's or not.

But keep in mind:
I am not responsible for any damage you made to your device or data.
You have been warned.

Daniel

**Comment by dafrenchyman** [comment]
You're amazing! I'm going to try this tonight when I get home. I'll hook up a drive I don't care about to it.

**Comment by dafrenchyman** [comment]
I tried it last night and I couldn't get it to work on 4.18. It compiled and installed fine, but when I rebooted it reached `r750` stuff during the boot and froze. I'll see if I can mess with 4.15 tonight.

**Comment by dsiggi** [comment]
Hi, how's it going? Have you already had a success?

**Comment by dafrenchyman** [comment]
Hi, I tried a bunch of times with different kernels and such, and couldn't get it to work. :-(

**Comment by dsiggi** [comment]
I'm sorry. So the patches for the RocketRaid series dosn't work with the rocket cards. It was worth a try. I hope you will find a solution to use your card with an actual kernel.

**Comment by AliensInc** [comment]
Hi

I just did a small test of this and it should work. I haven't implemented
it yet as I had an operation about a week ago. I've know about this
operation for quite some time and haven't had the energy to do anything yet.
The operation was a robot assisted laprascopic radical prostatectomy due to
a malignant prostate cancer.
So you might understand that my mind is not 100% on this now and I got
problems sitting normally.
This will be.tested though and used, but it have to wait a bit, I'll let
you know.

Thanks for asking though 🙂

//Oerjan

**Comment by dafrenchyman** [comment]
It may all be my fault. I'm not the most skilled at messing with kernels. It eventually did try loading `r750` stuff in the kernel during boot,.. but just froze there.

**Comment by Rudi9719** [comment]
Has there been any progress on this? I didn't even realize there was work being done on the r750 version and was actually going through your patches to try to implement them myself (which caused massive headaches in the 5.x kernel that comes with Ubuntu 20.04). I'd be happy to downgrade to 18.04 if this works though!
